Add summary for Grafana

diff --git a/.github/workflows/_03_Deployment_Appli.yml b/.github/workflows/_03_Deployment_Appli.yml
--- a/.github/workflows/_03_Deployment_Appli.yml
+++ b/.github/workflows/_03_Deployment_Appli.yml
@@ -75,6 +75,45 @@ jobs:
             --namespace monitoring \
             -f integration/helm/monitoring/monitoring-${{ inputs.environment }}.yaml
 
+      - name: Display Grafana URL
+        run: |
+          echo "Waiting for Grafana Ingress ALB URL..."
+
+          GRAFANA_INGRESS_URL=""
+
+          for i in {1..30}; do
+            GRAFANA_INGRESS_URL=$(kubectl get ingress monitoring-grafana \
+              -n monitoring \
+              -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
+
+            if [ -n "$GRAFANA_INGRESS_URL" ]; then
+              break
+            fi
+
+            echo "Grafana Ingress ALB not ready yet... retry $i/30"
+            sleep 10
+          done
+
+          if [ -z "$GRAFANA_INGRESS_URL" ]; then
+            echo "Grafana Ingress ALB URL not found"
+            kubectl describe ingress monitoring-grafana -n monitoring
+            exit 1
+          fi
+
+          GRAFANA_URL="https://microcrm-grafana.${{ inputs.environment }}.${{ vars.BASE_DOMAIN }}"
+
+          echo "Grafana ALB URL: https://$GRAFANA_INGRESS_URL"
+          echo "Grafana URL: $GRAFANA_URL"
+
+          echo "### Monitoring deployed" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "Grafana ALB URL: https://$GRAFANA_INGRESS_URL" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "Grafana URL: $GRAFANA_URL" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "OVH domain configuration: edit DNS record (CNAME)" >> $GITHUB_STEP_SUMMARY
+          echo "microcrm-grafana.${{ inputs.environment }} => $GRAFANA_INGRESS_URL." >> $GITHUB_STEP_SUMMARY
+          
       - name: Check monitoring
         run: |
           kubectl get pods -n monitoring
